name: Daily Commit

on:
  schedule:
   - cron: '51 15 * * *'  # 9:21 PM IST daily
  workflow_dispatch:        # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'adarsh-vishwakarma'
          git config --global user.email 'adarshvishwakarma704@gmail.com'

      - name: Run update script
        run: |
          chmod +x update.sh
          ./update.sh
