name: Daily Commit

on:
  schedule:
    - cron: '30 15 * * *'  # 9:00 PM IST daily
  workflow_dispatch:        # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'your-github-username'
          git config --global user.email 'your-email@example.com'

      - name: Run update script
        run: |
          chmod +x update.sh
          ./update.sh
