name: Daily Commit

on:
  schedule:
  - cron: '5 16 * * *'  # 9:35 PM IST (16:05 UTC)
  workflow_dispatch:        # Allow manual run

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config --global user.name "adarsh-vishwakarma"
          git config --global user.email "adarshvishwakarma704@gmail.com"

      - name: Run Node Script
        run: node update.js
